//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdioSoft.Site.Escalation.List {
    
    
    public partial class OpenList {
        
        /// <summary>
        /// Breadcrumb1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IdioSoft.Site.Escalation.Ucontrol.Breadcrumb Breadcrumb1;
        
        /// <summary>
        /// TabNav1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IdioSoft.Site.Escalation.Ucontrol.TabNav TabNav1;
        
        /// <summary>
        /// EscalationOperation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IdioSoft.Site.Escalation.List.EscalationOperation EscalationOperation1;
    }
}
